### ISSUE TITLE
Please add demo

### ISSUE THREAD

**Issue by doliG** [g-hanwen/hugo-theme-nostyleplease#23]
Would be great to have instant access to a demo website to know if this theme fits user needs :) Tell me if I can help

**Comment by imadnyc** [comment]
not a demo, but my website uses this if you just want to check it out https://imad.nyc/

**Comment by younsl** [comment]
@doliG I understand you need a demo for the nostyleplease theme. Check out my blog at [younsl.github.io](https://younsl.github.io) — it showcases [the theme's](https://github.com/hanwenguo/hugo-theme-nostyleplease) look and functionality.

**Comment by younsl** [comment]
@hanwenguo Just a light suggestion: it would be helpful to add a section called `adapters` in the README, listing user pages that use the nostyleplease theme. This can guide potential users with real examples.

**Comment by privacyseries** [comment]
> younsl.github.io

site looks nice  - thanks for sharing. Do you know a method for displaying/embedding videos on the template? I have tried a couple of ways, and it does not seem to work. :-(

**Comment by younsl** [comment]
@privacyseries Yes, sure. Video embedding within pages is not related to this theme and is handled by the Hugo framework. The simplest way is to use Hugo's built-in [Youtube shortcode](https://gohugo.io/shortcodes/youtube/). Just copy the ID after v= from the YouTube video URL and it will automatically embed the video on your page.

<details>
<summary>Example for Youtube shortcode</summary>

Example in content page file:

```yaml
---
title: "Example page embedding Youtube video"
date: 2022-08-31T15:38:15+09:00
lastmod: 2025-06-17T02:23:00+09:00
slug: ""
description: "about"
keywords: []
tags: ["bio", "profile"]
showAdvertisement: false
---

This page describes how to embed Youtube video in content page.

My video:

{{< youtube dQw4w9WgXcQ >}}
```

Hugo renders this to:

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/384e627c-9685-4c4c-b490-6dfe60cda824" />

</details>
